---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:

inputs:
  - name: source

outputs:
  - name: build

run:
  path: pcfdemo/ci/tasks/build.sh
  args: [
    --input-dir, java-shim,
    --output-dir, build
  ]
